"use client"

import AppContext from '@/Context/AppContext'
import './globals.css'
import { Inter } from 'next/font/google'
import NavDesk from '@/components/Navbar/NavDesk/NavDesk'
import React from 'react'
import Footer from '@/components/Footer/Footer'
import MenuHelper from '@/components/Menu/MenuHelper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gadget Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContext>
          <div>
            <NavDesk />
            <MenuHelper />
            {children}
            <Footer />
          </div>
        </AppContext>
      </body>
    </html>
  )
}
