"use client"

import AppContext from '@/Context/AppContext'
import './globals.css'
import { Inter } from 'next/font/google'
import NavDesk from '@/components/Navbar/NavDesk/NavDesk'
import React from 'react'
import Footer from '@/components/Footer/Footer'
import MenuHelper from '@/components/Menu/MenuHelper'
import ToggoleBtn from '@/components/ToggoleBtn/ToggoleBtn';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gadget Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContext>

          <div className='relative'>

            {/* <NavDesk /> */}

            {/* <MenuHelper /> */}

            {/* <div className='absolute top-[20px] right-[100px] lg:right-2 lg:top-[220px] z-[99]'><ToggoleBtn /></div> */}

            {children}

            {/* <Footer /> */}

          </div>

        </AppContext>
      </body>
    </html>
  )
}
